### PR TITLE
Fixed SMM_UNREG_HNDL can unregister any handler, including supervisor ones

### LINKED ISSUE #11: SMM_UNREG_HNDL can unregister any handler, including supervisor ones
The supervisor handles syscalls to register and unregister handlers on user space's behalf by exposing a SMM_REG_HNDL and SMM_UNREG_HNDL syscall. for registration it calls MmiUserHandlerRegister() to do this work, which calls CoreMmiHandlerRegister() with IsSupervisorHandler set to FALSE. For unregistering, it calls MmiHandlerUnRegister() with a user-provided handle. It performs a handle lookup and, if found, unregisters the handler. MmiHandlerUnRegister() makes no effort to see whether the handler's IsSupervisor BOOLEAN is set or not. In order words, a user-space caller can unregister a supervisor-created handler.

The impact of unregistering supervisor handler could potentially miss some events and potentially lose capability of reporting secure policy. However, security critical events will be enforced by the time external entities fetch the policy, or the OS will indicate system guard is off.

Fix recommendation:
Added a MmiUserHandlerUnRegister() function that makes sure only handlers with their IsSupervisor field set to FALSE can be unregistered through the SMM_UNREG_HNDL syscall.

Acknowledgement:
Thanks to @iljavs for reporting this issue.

### PR DESCRIPTION
**Pull request by kuqin12**
Bug Description:
The supervisor handles syscalls to register and unregister handlers on user space's behalf by exposing a SMM_REG_HNDL and SMM_UNREG_HNDL syscall. for registration it calls MmiUserHandlerRegister() to do this work, which calls CoreMmiHandlerRegister() with IsSupervisorHandler set to FALSE. For unregistering, it calls MmiHandlerUnRegister() with a user-provided handle. It performs a handle lookup and, if found, unregisters the handler. MmiHandlerUnRegister() makes no effort to see whether the handler's IsSupervisor BOOLEAN is set or not. In order words, a user-space caller can unregister a supervisor-created handler.

The impact of unregistering supervisor handler could potentially miss some events and potentially lose capability of reporting secure policy. However, security critical events will be enforced by the time external entities fetch the policy, or the OS will indicate system guard is off.

Fix:
Added a MmiUserHandlerUnRegister() function that makes sure only handlers with their IsSupervisor field set to FALSE can be unregistered through the SMM_UNREG_HNDL syscall.

fixes #11

### CODE REVIEW

File: MmSupervisorPkg/Core/Handler/Mmi.c [hunk 1]
```diff
@@ -341,18 +341,21 @@ MmiUserHandlerRegister (
...
-  Unregister a handler in MM.
+  Unregister a handler in MM with specified ownership.
 
-  @param  DispatchHandle  The handle that was specified when the handler was registered.
+  @param  DispatchHandle        The handle that was specified when the handler was registered.
+  @param  IsSupervisorHandler   The flag to indicate this is intending to unregister user or
+                                supervisor handler.
 
   @retval EFI_SUCCESS           Handler function was successfully unregistered.
   @retval EFI_INVALID_PARAMETER DispatchHandle does not refer to a valid handle.
```
Comment (makubacki) [inline MmSupervisorPkg/Core/Handler/Mmi.c:351]: You could update the `EFI_INVALID_PARAMETER` parameter description.

**Review by makubacki — APPROVED** [review]

File: MmSupervisorPkg/Core/Handler/Mmi.c (hunk 1 above)
Comment (kuqin12) [reply MmSupervisorPkg/Core/Handler/Mmi.c]: Thanks, updated!

**Review by spbrogan — APPROVED** [review]
