### PR TITLE
Fix integer overflow in IsIoReadWriteAllowed()

### LINKED ISSUE #6: Potential integer overflow in IsIoReadWriteAllowed()
The supervisor calls IsIoReadWriteAllowed() to see if a user can read or write to specific io ports. The code looks pretty decent; however, a few minor things seem wrong. There's some weirdness around casting and truncating when calling it (and when later using the ioports), which looks kinda bad, but ultimately it doesn't seem to cause much problems.

When validating the ioport and size, there is an integer overflow. It will overflow if the port is really big (0xfffffffd or larger). If there is a policy to allow writes to low ports (e.g., 0), then it could allow writing to a high port (e.g., 65535, 0xffffffff truncated to 16 bits). Ultimately this is a really specific set of circumstances and probably not that big of a deal, but it does look like a clear bug that should be addressed.

Fix recommendation:
A safe int function to convert port (IoAddress) to prevent any integer overflow from occurring. Also added an integer overflow check as a defense in depth mechanism.

Acknowledgement:
Thanks to @iljavs for reporting this issue.

### PR DESCRIPTION
**Pull request by kuqin12**
Bug Description:
The supervisor calls IsIoReadWriteAllowed() to see if a user can read or write to specific io ports. The code looks pretty decent; however, a few minor things seem wrong. There's some weirdness around casting and truncating when calling it (and when later using the ioports), which looks kinda bad, but ultimately it doesn't seem to cause many problems.

When validating the ioport and size, there is an integer overflow. It will overflow if the port is really big (0xfffffffd or larger). If there is a policy to allow writes to low ports (e.g., 0), then it could allow writing to a high port (e.g., 65535, 0xffffffff truncated to 16 bits). Ultimately this is a really specific set of circumstances and probably not that big of a deal, but it does look like a clear bug that should be addressed.

Fix:
A safe int function to convert port (IoAddress) to prevent any integer overflow from occurring. Also added an integer overflow check as a defense in depth mechanism.

fixes #6

### CODE REVIEW

File: MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c [hunk 1]
```diff
@@ -78,6 +80,27 @@ IsIoReadWriteAllowed (
...
+    Status = EFI_INVALID_PARAMETER;
+    goto Exit;
+  }
+
+  //
+  // Check to ensure the ending IO port number is within the range of 16bit value
+  // The MAX_UINT16 + 1 is because access 1 byte at 0xFFFF is still legit, if needed
+  //
+  if (IoAddress + IoSize > MAX_UINT16 + 1) {
+    // IO port 0xFFFF with width of
```
Comment (spbrogan) [inline MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c:98]: incomplete comment

**Review by spbrogan — APPROVED** [review]

File: MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c (hunk 1 above)
Comment (makubacki) [inline MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c:98]: Looks like this comment is incomplete

**Review by makubacki — APPROVED** [review]

File: MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c (hunk 1 above)
Comment (makubacki) [reply MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c:98]: I see Sean also mentioned this. I'll close this comment.

Comment (kuqin12) [reply MmSupervisorPkg/Library/SmmPolicyGateLib/SmmPolicyGateLib.c]: This is removed.
